var myFullName;
console.log(myFullName);
console.log("------------------------------");
myFullName="Priyanka Gaikwad";
console.log("Name            -",myFullName);
console.log("------------------------------");
myFullName="Priyanka Akshay Gaikwad";
console.log("Full Name       -",myFullName);
console.log("------------------------------");
var myLove="I Love only JS";
console.log("My Love         -",myLove);
var firstName="Priyanka";
var lastName="Gaikwad";
var age=25;
var address="Pimple Saudagar,pune";
var pinCode=411027;
var gender="female";
var isMarried=true;
console.log(" First Name            -",firstName);
console.log(" Last Name            -",lastName);
console.log("My Age                -",age);
console.log("Address               -",address);
console.log("Pincode               -",pinCode);
console.log("gender                -",gender);
console.log("Married Status        -",isMarried);
console.log("------------------------------");

